PAYPAL_CLIENT_ID: "AXU6AIP4k7s2UeVk_l9r5h4hnci4bYEm3fWn6xlUIRZ8Dfzc0V25Lp6whsx2KnUgCrjU1aYGSTEoN8TG"
PAYPAL_CLIENT_SECRET: "EDO4qhbFwfkSbRbhZMIEenJY7QIOBxyCR8W3Qp6lcVLj1DoFt9vUYTb-T8CIKGprQJVFTN7vIzx3dhxi"
test: &default
  PAYPAL_ENV: sandbox
  PAYPAL_CLIENT_ID: 	 	AXU6AIP4k7s2UeVk_l9r5h4hnci4bYEm3fWn6xlUIRZ8Dfzc0V25Lp6whsx2KnUgCrjU1aYGSTEoN8TG
  PAYPAL_CLIENT_SECRET: 	EDO4qhbFwfkSbRbhZMIEenJY7QIOBxyCR8W3Qp6lcVLj1DoFt9vUYTb-T8CIKGprQJVFTN7vIzx3dhxi

development:
  <<: *default